apiVersion: apps/v1
kind: Deployment
metadata:
  name: flashcard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flashcard-frontend
  template:
    metadata:
      labels:
        app: flashcard-frontend
    spec:
      containers:
        - name: flashcard-frontend
          image: tiana25/flashcard-frontend:latest
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_BASE
              value: http://localhost:31888
---
apiVersion: v1
kind: Service
metadata:
  name: flashcard-frontend
spec:
  selector:
    app: flashcard-frontend
  ports:
    - port: 5173
      targetPort: 5173
  type: LoadBalancer
